### ISSUE TITLE
Question: I'm writing a test and it complains about magic numbers

### ISSUE THREAD

**Issue by tomer-ben-david** [marconilanna/scala-boilerplate#1]
``` scala
class Solution extends FlatSpec with ShouldMatchers {
  "the solution" should "find the last element of a list" in {
    last(List(1, 1, 2, 3, 5, 8)) // it complains here that I have magic numbers.
  }

  def last(input: Seq[Int]): Int = input.last
}
```

is there anything i'm doing wrong? how do you get along with it complaining about such stuff in tests?

**Comment by marconilanna** [comment]
You can use comment filters: http://www.scalastyle.org/configuration.html#comment_filters

In the general case, it would make more sense to create a separate, more relaxed `scalastyle-test-config.xml` for tests: http://www.scalastyle.org/sbt.html#running_scalastyle_on_your_test_sources
